### ISSUE TITLE
Color of uploaded image is off

### ISSUE THREAD

**Issue by swelland** [zploskey/ExperimentalBeijing#18]
I uploaded a few new images today, and I noticed that the color of a few on the website is discernibly different from the original jpeg, when viewed on the same monitor. Here's an example: http://depts.washington.edu/expbj/ExperimentalBeijing/items/show/732. Attached is the jpeg I uploaded. 

Any ideas about what's going on?

![fig 0 01](https://user-images.githubusercontent.com/13439922/29297267-9e91dee0-8114-11e7-9780-b143304ef1e3.jpg)

**Comment by zploskey** [comment]
I can't tell the difference between the two images. Omeka does do some image processing to generate thumbnails and the fullsize images that are shown on item pages. This is done using imagemagick by default. I don't think it should be changing colors though.

**Comment by zploskey** [comment]
All I can figure here is there may be subtle changes to the average color in the pixels of an image that has been reduced in size (for thumbnails, preview images, etc). Omeka generates several different sizes of each uploaded image. Currently I've made some modifications so that the original uploaded image is displayed in a lightbox when clicking on the images in the item page. Since it's the original file there should hopefully be no color difference.
