### ISSUE TITLE
Moving image/video item page layout

### ISSUE THREAD

**Issue by swelland** [zploskey/ExperimentalBeijing#4]
See example here: http://depts.washington.edu/expbj/ExperimentalBeijing/items/show/734. The layout is a bit wonky, I think, because the video image needs to be constrained according to the standard dimensions provided by Siyi. Is there is a way to add the full screen button to bottom of the video box. You can get to it by clicking on the CC (Critical Commons) logo and opening in it through their webpage for the clip, but it would more streamlined to be able to get to it straight from the Omeka item page.

**Comment by zploskey** [comment]
I've fixed the layout issues on my copy so that we don't have any overlap of the text and the video. I'll go ahead and push those changes.

The fullscreen issues are a little more complicated. The full screen controls are actually there but the controls are not loading their background images correctly (so the full screen button does not display its icon). This is a problem with the default code for the iframe referring to those images locally. We could process the received iframe, but ideally Creative Commons should fix their iframe code to use the full link to `controls.svg`. I think you mentioned that you know them, so perhaps you can you can talk to them about it.

If you click the spot where the fullscreen button should be it will fullscreen the video but only within the iframe, so it doesn't get much bigger. We need to add the `allowfullscreen` attribute to the iframe, which I can either do in the code or we can add it to each of the iframes that we add.

**Comment by swelland** [comment]
Thanks for working on this. I see what you mean now about the volume and fullscreen buttons not showing. In Firefox, when I click on the fullscreen spot, it does a weird thing where it pops out to fullscreen and then back again. 

I will contact Critical Commons to ask them about the problem with their iframe code.

**Comment by zploskey** [comment]
I think it leaves full screen because it can't load some of the images that appear when going to full screen. If they fix their iframe code it should hopefully stay fullscreen.

**Comment by swelland** [comment]
I have a message out to Critical Commons on the iframe code.

I think you've probably already noticed this, but now that the video item page layout is fixed, the layout for the image item pages is messed up. See for example: http://depts.washington.edu/expbj/ExperimentalBeijing/items/show/921

**Comment by zploskey** [comment]
Sweet. The layout issue should be fixed now.

**Comment by zploskey** [comment]
Layout issue is fixed. Popping out of fullscreen in Firefox seems to be a Critical Commons problem.
